### ISSUE TITLE
VS2015: System.ArgumentNullException: Value cannot be null. Parameter name: service Provider at Microsoft.AppInsights.GettingStarted.Telemetry.SKUHelper.GetSKU

### ISSUE THREAD

**Issue by Twoleeland** [Microsoft/ApplicationInsights-SDK-Labs#95] opened 2017-03-06 12:46 UTC
Hello,

I get this error each time, when I start VS2015 and opening a VB class file (.aspx.vb or .vb) the first time after starting VS2015. The error is only showing one time after each start of VS2015. The error only appears in version 7.18 of AppInsight, regardless if CodeLens is enabled or not. With version 7.12 this error doesn't appear.

The following entry is written in the ActivityLog.xml:
`
<entry>
    <record>1114</record>
    <time>2017/03/06 12:36:50.132</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: serviceProvider&#x000D;&#x000A;   at Microsoft.AppInsights.GettingStarted.Telemetry.SKUHelper.GetSKU(IServiceProvider serviceProvider)&#x000D;&#x000A;   at Microsoft.AppInsights.GettingStarted.CodeLens.CodeLensVBMarginProvider.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__25_1(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)</description>
  </entry>`

**Comment by SergeyKanzhelev** [comment] 2017-03-06 17:06
@gardnerjr can you please look at this one?

**Comment by gardnerjr** [comment] 2017-03-06 18:09
Can do.  have escalated it internally.  @Twoleeland are you opening an entire solution or just a VB file by itself?

**Comment by gardnerjr** [comment] 2017-03-06 18:23
Internally: Bug 941257: System.ArgumentNullException: Value cannot be null. Parameter name: service Provider at Microsoft.AppInsights.GettingStarted.Telemetry.SKUHelper.GetSKU

**Comment by paruizfi** [comment] 2017-03-06 22:57
We were unable to reproduce this issue, tried opening a vb file in a solution and vb file on its own. Are you getting any other errors before this happens?

**Comment by Twoleeland** [comment] 2017-03-07 08:12
I'm sorry, but I think, I posted it wrong. :-/ Please, excuse the inconveniences! I didn't mean the SDK, I meant the "Developer Analytics Tools"-extension, which includes AppInsights. I wrote a feedback through VS 2015 for this problem. Thanks a lot anyway! :-)

**Comment by SergeyKanzhelev** [comment] 2017-03-07 16:59
Closing the issue here

**Closed by SergeyKanzhelev** 2017-03-07 16:59 UTC

**Comment by OmerRaviv** [comment] 2017-03-16 16:03
@Twoleeland Can you please reference the ticket you opened through VS2015? I'm seeing this issue as well

**Comment by gardnerjr** [comment] 2017-03-16 16:08
@OmerRaviv what's your full repro steps?  (and is this also against 7.18 of the developer analytics tools?)  We're trying to repro this to fix it, but we've never seen the problem so there might just be something subtle in what we're doing that doesn't match what you guys are, or what else you might have installed?

**Comment by OmerRaviv** [comment] 2017-03-16 17:14
@gardnerjr I actually haven't been able to repro this myself either, still trying. I'm authoring a VS extension (http://www.oz-code.com) and had a customer complain about getting this error right after installing my extension. 

The customer has version 7.18.00214.2 of the developer analytics tools installed on VS2015 Enterprise Version 14.0.25431.01 Update 3.

**Comment by OmerRaviv** [comment] 2017-03-22 12:25
Here's what the customer who's experienced this has installed: 

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055
 
Installed Version: Enterprise
 
Architecture and Modeling Tools   00322-90001-94463-AA979
Microsoft Architecture and Modeling Tools
   
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.
 
Visual Basic 2015   00322-90001-94463-AA979
Microsoft Visual Basic 2015
 
Visual C# 2015   00322-90001-94463-AA979
Microsoft Visual C# 2015
 
Visual C++ 2015   00322-90001-94463-AA979
Microsoft Visual C++ 2015
 
Application Insights Tools for Visual Studio Package   7.18.00214.2
Application Insights Tools for Visual Studio
 
ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)
 
ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
 
ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/
 
CodeMaid   10.2.7
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.
 
Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
 
JavaScript Language Service   2.0
JavaScript Language Service
 
JavaScript Project System   2.0
JavaScript Project System
 
JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.
 
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools
 
NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
 
Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU
 
Oracle Developer Tools for Visual Studio   12.1.0.2.4
Oracle Developer Tools for Visual Studio Copyright (c) 2005, 2015
 
PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
 
Web Essentials 2015.3   3.0.235
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015
 
Windows Installer XML Toolset   3.10.3.3007
Windows Installer XML Toolset version 3.10.3.3007
Copyright (c) .NET Foundation and contributors. All rights reserved.

**Comment by johnrah** [comment] 2017-03-24 06:45
I have the same error appearing but with Blend 2015.  VS 2015 is not showing this error for me.  
Typically I will select Design With Blend from VS and this error appears.  
I've attached the activity log.  Record 508 is where the error occurs.
This only started happening after installing VS2107 RC


[ActivityLog.xml.txt](https://github.com/Microsoft/ApplicationInsights-SDK-Labs/files/867083/ActivityLog.xml.txt)

**Comment by gardnerjr** [comment] 2017-03-24 18:29
Huh.  our extension shouldn't be loading in Blend, so that's problem 0.  somehow it is loading our editor extension, but not our package.  that should not be happening.  The fact that it started happening in Blend 2015 after installing VS2017 of any flavor would be even more troublesome as the 2 should be completely unrelated.  

@johnrah Is the project you're opening in blend configured in any way with application insights?  or you just get this all the time with any project?

**Comment by johnrah** [comment] 2017-03-25 02:56
I've done a bit of digging around.  The solution itself doesn't have any reference to App. Insights. However, the solution is part of a Visual Studio Team Services project which has another solution in it for an Azure Web Service (WebAPI) and that does have Application Insights as a Service Reference.
Is it possible that the Team Explorer is the culprit?  Even though I'm not loading the WebAPI solution in Blend it is coming up in the list of solutions in Team Explorer.  The error only appears on first launch of Blend, my guess is when it's populating Team Explorer.

**Comment by OmerRaviv** [comment] 2017-03-27 15:30
@gardnerjr FYI I've had another customer report this issue happening immediately after installing OzCode (in VS), but he reported that after restarting VS, the problem went away and never came back.

As for Blend - it makes sense that this code will cause Blend to fail. The fact that Blend is loading your MEF extensions even though it doesn't load your package is unfortunately just the way Blend works, and there isn't much you can do about it other than rewrite your MEF Components to make them resilient to it (we've had the same problem in the past with OzCode). I'm quoting part of an email discussion with @mgoertz-msft which might be helpful:

> 
> Blend currently only knows how to not load packages based on their package guids. By their nature MEF components are unfortunately not part of that logic, at least not yet.
> 
> I noticed that your extension is installed via MSI. I know it sounds counterintuitive but if you were to change your install folder from Common7\IDE\Extensions to Common7\IDE\CommonExtensions then Blend would not load any of your components. The reason for that is that Blend only considers certain folders under CommonExtensions but everything under Extensions.
> ...
> Eventually we hope to figure out a way to associate MEF components with packages but for VS 2015 this is probably the best and perhaps even only way.
> 
>

**Comment by AdamWaw** [comment] 2017-03-31 17:48
I have same happening to me every time I open Blend (2015, Update 3):

1 error:
System.ArgumentNullException: Value cannot be null. Parameter name: serviceProvider at Microsoft.AppInsights.GettingStarted.Telemetry.SKUHelper.GetSKU(IServiceProvider serviceProvider) at Microsoft.AppInsights.GettingStarted.Telemetry.SKUHelper.get_IsExpressSKU() at Microsoft.AppInsights.GettingStarted.CodeLens.CodeLensCSharpMarginProvider.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.<AddMargins>b__25_1(IWpfTextViewMarginProvider mp) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)

2 error:
System.ArgumentNullException: Value cannot be null. Parameter name: serviceProvider at Microsoft.AppInsights.GettingStarted.Telemetry.SKUHelper.GetSKU(IServiceProvider serviceProvider) at Microsoft.AppInsights.GettingStarted.Telemetry.SKUHelper.get_IsExpressSKU() at Microsoft.AppInsights.GettingStarted.CodeLens.CodeLensCSharpMarginProvider.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.<AddMargins>b__25_1(IWpfTextViewMarginProvider mp) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)

**Comment by jozefizso** [comment] 2017-04-19 12:58
I have the same issue, stock Visual Studio 2015 Update 3 without any 3rd party extensions installed.

```
System.ArgumentNullException: Value cannot be null. Parameter name: serviceProvider at Microsoft.AppInsights.GettingStarted.Telemetry.SKUHelper.GetSKU(IServiceProvider serviceProvider) at Microsoft.AppInsights.GettingStarted.CodeLens.CodeLensCSharpMarginProvider.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.<AddMargins>b__25_1(IWpfTextViewMarginProvider mp) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)
```

**Comment by gardnerjr** [comment] 2017-04-21 21:12
We have shipped an update to our tools for VS2015 Update 3, version 7.19:
[https://marketplace.visualstudio.com/items?itemName=VisualStudioOnlineApplicationInsights.DeveloperAnalyticsTools](https://marketplace.visualstudio.com/items?itemName=VisualStudioOnlineApplicationInsights.DeveloperAnalyticsTools)

which should fix this.  Unfortunately, i believe that the microsoft signing certificate has been updated, and the VS Auto Updater only allows it to auto update things that have the same certificate as the old version.  So you may have to manually update in the tools->extensions and updates window in VS.

**Comment by AdamWaw** [comment] 2017-04-24 13:58
This has fixed my issue, thank you.
