### ISSUE TITLE
System.ObjectDisposedException 

### ISSUE THREAD

**Issue by rahul24** [Microsoft/ApplicationInsights-SDK-Labs#87] opened 2016-12-31 05:00 UTC
There are lots of such traces are getting logged in app insights. 

AI (Internal): [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.Wcf.UserAgentTelemetryInitializer, exception message - System.ObjectDisposedException: Message is closed.
   at System.ServiceModel.Channels.BufferedMessage.get_Properties()
   at Microsoft.ApplicationInsights.Wcf.Implementation.WcfOperationContext.HasIncomingMessageProperty(String propertyName)
   at Microsoft.ApplicationInsights.Wcf.Implementation.WcfExtensions.GetHttpRequestHeaders(IOperationContext operation)
   at Microsoft.ApplicationInsights.Wcf.UserAgentTelemetryInitializer.OnInitialize(ITelemetry telemetry, IOperationContext operation)
   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]

**Comment by tomasr** [comment] 2017-01-02 16:41
Is this the only exception of this type that you're seeing? I've been trying to track these (unsuccessfully) for a while now without much success.

They might be related to other WCF behaviors being present in the stack and the order they run into, but not sure which ones yet, so any additional information you can provide on your setup would definitely help!

There's also the fact that `OperationContext` in WCF does not provide a way to track if the corresponding messages are disposed or not directly :smile:.

**Comment by rahul24** [comment] 2017-01-02 18:12
Yes, only getting DisposedExcetion in different initializers. Even, for me this one is not coming in local setup but occurring when code is in action (deployed). What if we check "IsDispose" property before accessing that BufferedMessage.get_Properties() or any pointers would be helpful to fix for same?

**Comment by tomasr** [comment] 2017-01-02 18:17
The problem is that we don't have access to the actual message object (WCFs `IOperationContext` wraps the message and provides access to the headers/properties, but no way to check if the message is not disposed before accessing it).

I have certainly thought to add some exception catchers for this, but it would still lead to a telemetry event produced that would simply have some information missing from the context.

So the key question I'd like to get to the bottom of is: *What is causing us to look at a message that is already disposed?*

The only way I can sort of think this could happen is if another extension consumed and disposed the message before we look into it, and that would need to be either when we're producing the telemetry event for the request or an exception. The latter is likely more probable since it could happen in an async scenario, I think.

**Comment by rahul24** [comment] 2017-01-03 18:44
I'm able to reproduce this problem by using directions you provided above. This problem would generally come when the call to external service has made asynchronously from within the ongoing request.  In my case, I hooked endpoint behavior with all external services (client) to track the dependency with proper values (i.e. operation name and time taken). So, when any call to external services has been made from within any API asynchronously then this problem would occur. I handled\resolved this scenario by wrapping the incoming message properties of operationcontext with try/catch and return false or default value (null / empty). Secondly, getting the operation id from operation context before sending a message to the client (so if the object gets disposed of will able to relate/track service dependency with the particular request).

Thanks @tomasr for your help.

**Comment by tomasr** [comment] 2017-01-03 18:51
That's interesting. So if I get this right, inside your service operation code you're initiating an async call to a service, then returning a response, and the service call is completing *after* the operation has returned, is that right?

If this is indeed the case, then yes, this would be sort of expected, but there might be a way to prevent it, if the Request telemetry object is still around. Let me try to set up a repro in this case and try to come up with some alternatives!

**Comment by rahul24** [comment] 2017-01-03 19:03
Yes, that's correct. As a fix, am getting the values (i.e. operationid of request) and associating with service dependency before initiating the external call  asynchronously. This way will able to associate request and dependency. But, since message is disposed therefore some of properties goes without initialized like user, session object of context (these initializers throws error which would handled by wrapping in try/catch). Any other approach you can think of then do share with me? I've created a demo app to reproduce this problem. If you need would help you with same.

**Comment by tomasr** [comment] 2017-01-04 19:10
The updated NuGet package (0.26.0-build56865) is now published. Can you give it a try and see if it works better for you?

**Comment by rahul24** [comment] 2017-01-06 06:33
Sure. Will try and let you know.

**Comment by tomasr** [comment] 2017-08-23 22:56
Closing as we have not had any more reports of this.

**Closed by tomasr** 2017-08-23 22:56 UTC
